<a href="https://colab.research.google.com/github/Yoo-Ha-young/first_repo/blob/main/221107_first_note_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.7.15

In [ ]:
!pip --version

pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)

In [ ]:
!pip list

Package                       Version
----------------------------- ----------------------
absl-py                       1.3.0
aeppl                         0.0.33
aesara                        2.7.9
aiohttp                       3.8.3
aiosignal                     1.2.0
alabaster                     0.7.12
albumentations                1.2.1
altair                        4.2.0
appdirs                       1.4.4
arviz                         0.12.1
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
async-timeout                 4.0.2
asynctest                     0.13.0
atari-py                      0.2.9
atomicwrites                  1.4.1
attrs                         22.1.0
audioread                     3.0.0
autograd                      1.5
Babel                         2.10.3
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        5.0.1
blis                          0.7.9
bokeh                         2.3.3
branca                        0.5.0
bs4                           0.0.1
CacheControl                  0.12.11
cached-property               1.5.2
cachetools                    4.2.4
catalogue                     2.0.8
certifi                       2022.9.24
cffi                          1.15.1
cftime                        1.6.2
chardet                       3.0.4
charset-normalizer            2.1.1
click                         7.1.2
clikit                        0.6.2
cloudpickle                   1.5.0
cmake                         3.22.6
cmdstanpy                     1.0.8
colorcet                      3.0.1
colorlover                    0.3.0
community                     1.0.0b1
confection                    0.0.3
cons                          0.4.5
contextlib2                   0.5.5
convertdate                   2.4.0
crashtest                     0.3.1
crcmod                        1.7
cufflinks                     0.17.3
cvxopt                        1.3.0
cvxpy                         1.2.1
cycler                        0.11.0
cymem                         2.0.7
Cython                        0.29.32
daft                          0.0.4
dask                          2022.2.0
datascience                   0.17.5
debugpy                       1.0.0
decorator                     4.4.2
defusedxml                    0.7.1
descartes                     1.1.0
dill                          0.3.6
distributed                   2022.2.0
dlib                          19.24.0
dm-tree                       0.1.7
dnspython                     2.2.1
docutils                      0.17.1
dopamine-rl                   1.0.5
earthengine-api               0.1.329
easydict                      1.10
ecos                          2.0.10
editdistance                  0.5.3
en-core-web-sm                3.4.1
entrypoints                   0.4
ephem                         4.1.3
et-xmlfile                    1.1.0
etils                         0.8.0
etuples                       0.3.8
fa2                           0.3.5
fastai                        2.7.9
fastcore                      1.5.27
fastdownload                  0.0.7
fastdtw                       0.3.4
fastjsonschema                2.16.2
fastprogress                  1.0.3
fastrlock                     0.8
feather-format                0.4.1
filelock                      3.8.0
firebase-admin                4.4.0
fix-yahoo-finance             0.0.22
Flask                         1.1.4
flatbuffers                   1.12
folium                        0.12.1.post1
frozenlist                    1.3.1
fsspec                        2022.10.0
future                        0.16.0
gast                          0.4.0
GDAL                          2.2.2
gdown                         4.4.0
gensim                        3.6.0
geographiclib                 1.52
geopy                         1.17.0
gin-config                    0.5.0
glob2                         0.7
google                        2.0.3
google-api-core               1.31.6
google-api-python-client      1.12.11
google-auth                   1.35.0
google-auth-httplib2          0.0.4
google-auth-oauthlib          0.4.6
google-cloud-bigquery         1.21.0
google-cloud-bigquery-storage 1.1.2
google-cloud-core             1.0.3
google-cloud-datastore        1.8.0
google-cloud-firestore        1.7.0
google-cloud-language         1.2.0
google-cloud-storage          1.18.1
google-cloud-translate        1.5.0
google-colab                  1.0.0
google-pasta                  0.2.0
google-resumable-media        0.4.1
googleapis-common-protos      1.56.4
googledrivedownloader         0.4
graphviz                      0.10.1
greenlet                      1.1.3.post0
grpcio                        1.50.0
gspread                       3.4.2
gspread-dataframe             3.0.8
gym                           0.25.2
gym-notices                   0.0.8
h5py                          3.1.0
HeapDict                      1.0.1
hijri-converter               2.2.4
holidays                      0.16
holoviews                     1.14.9
html5lib                      1.0.1
httpimport                    0.5.18
httplib2                      0.17.4
httplib2shim                  0.0.3
httpstan                      4.6.1
humanize                      0.5.1
hyperopt                      0.1.2
idna                          2.10
imageio                       2.9.0
imagesize                     1.4.1
imbalanced-learn              0.8.1
imblearn                      0.0
imgaug                        0.4.0
importlib-metadata            4.13.0
importlib-resources           5.10.0
imutils                       0.5.4
inflect                       2.1.0
intel-openmp                  2022.2.0
intervaltree                  2.1.0
ipykernel                     5.3.4
ipython                       7.9.0
ipython-genutils              0.2.0
ipython-sql                   0.3.9
ipywidgets                    7.7.1
itsdangerous                  1.1.0
jax                           0.3.23
jaxlib                        0.3.22+cuda11.cudnn805
jieba                         0.42.1
Jinja2                        2.11.3
joblib                        1.2.0
jpeg4py                       0.1.4
jsonschema                    4.3.3
jupyter-client                6.1.12
jupyter-console               6.1.0
jupyter-core                  4.11.2
jupyterlab-widgets            3.0.3
kaggle                        1.5.12
kapre                         0.3.7
keras                         2.9.0
Keras-Preprocessing           1.1.2
keras-vis                     0.4.1
kiwisolver                    1.4.4
korean-lunar-calendar         0.3.1
langcodes                     3.3.0
libclang                      14.0.6
librosa                       0.8.1
lightgbm                      2.2.3
llvmlite                      0.39.1
lmdb                          0.99
locket                        1.0.0
logical-unification           0.4.5
LunarCalendar                 0.0.9
lxml                          4.9.1
Markdown                      3.4.1
MarkupSafe                    2.0.1
marshmallow                   3.18.0
matplotlib                    3.2.2
matplotlib-venn               0.11.7
miniKanren                    1.0.3
missingno                     0.5.1
mistune                       0.8.4
mizani                        0.7.3
mkl                           2019.0
mlxtend                       0.14.0
more-itertools                9.0.0
moviepy                       0.2.3.5
mpmath                        1.2.1
msgpack                       1.0.4
multidict                     6.0.2
multipledispatch              0.6.0
multitasking                  0.0.11
murmurhash                    1.0.9
music21                       5.5.0
natsort                       5.5.0
nbconvert                     5.6.1
nbformat                      5.7.0
netCDF4                       1.6.1
networkx                      2.6.3
nibabel                       3.0.2
nltk                          3.7
notebook                      5.5.0
numba                         0.56.3
numexpr                       2.8.4
numpy                         1.21.6
oauth2client                  4.1.3
oauthlib                      3.2.2
okgrade                       0.4.3
opencv-contrib-python         4.6.0.66
opencv-python                 4.6.0.66
opencv-python-headless        4.6.0.66
openpyxl                      3.0.10
opt-einsum                    3.3.0
osqp                          0.6.2.post0
packaging                     21.3
palettable                    3.3.0
pandas                        1.3.5
pandas-datareader             0.9.0
pandas-gbq                    0.13.3
pandas-profiling              1.4.1
pandocfilters                 1.5.0
panel                         0.12.1
param                         1.12.2
parso                         0.8.3
partd                         1.3.0
pastel                        0.2.1
pathlib                       1.0.1
pathy                         0.6.2
patsy                         0.5.3
pep517                        0.13.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        7.1.2
pip                           21.1.3
pip-tools                     6.2.0
plotly                        5.5.0
plotnine                      0.8.0
pluggy                        0.7.1
pooch                         1.6.0
portpicker                    1.3.9
prefetch-generator            1.0.1
preshed                       3.0.8
prettytable                   3.4.1
progressbar2                  3.38.0
promise                       2.3
prompt-toolkit                2.0.10
prophet                       1.1.1
protobuf                      3.17.3
psutil                        5.4.8
psycopg2                      2.9.5
ptyprocess                    0.7.0
py                            1.11.0
pyarrow                       6.0.1
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycocotools                   2.0.5
pycparser                     2.21
pyct                          0.4.8
pydantic                      1.10.2
pydata-google-auth            1.4.0
pydot                         1.3.0
pydot-ng                      2.0.0
pydotplus                     2.0.2
PyDrive                       1.3.1
pyemd                         0.5.1
pyerfa                        2.0.0.1
Pygments                      2.6.1
pygobject                     3.26.1
pylev                         1.4.0
pymc                          4.1.4
PyMeeus                       0.5.11
pymongo                       4.3.2
pymystem3                     0.2.0
PyOpenGL                      3.1.6
pyparsing                     3.0.9
pyrsistent                    0.18.1
pysimdjson                    3.2.0
pysndfile                     1.3.8
PySocks                       1.7.1
pystan                        3.3.0
pytest                        3.6.4
python-apt                    0.0.0
python-dateutil               2.8.2
python-louvain                0.16
python-slugify                6.1.2
python-utils                  3.3.3
pytz                          2022.5
pyviz-comms                   2.2.1
PyWavelets                    1.3.0
PyYAML                        6.0
pyzmq                         23.2.1
qdldl                         0.1.5.post2
qudida                        0.0.4
regex                         2022.6.2
requests                      2.23.0
requests-oauthlib             1.3.1
resampy                       0.4.2
rpy2                          3.5.5
rsa                           4.9
scikit-image                  0.18.3
scikit-learn                  1.0.2
scipy                         1.7.3
screen-resolution-extra       0.0.0
scs                           3.2.0
seaborn                       0.11.2
Send2Trash                    1.8.0
setuptools                    57.4.0
setuptools-git                1.2
Shapely                       1.8.5.post1
six                           1.15.0
sklearn-pandas                1.8.0
smart-open                    5.2.1
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soundfile                     0.11.0
spacy                         3.4.2
spacy-legacy                  3.0.10
spacy-loggers                 1.0.3
Sphinx                        1.8.6
sphinxcontrib-serializinghtml 1.1.5
sphinxcontrib-websupport      1.2.4
SQLAlchemy                    1.4.42
sqlparse                      0.4.3
srsly                         2.4.5
statsmodels                   0.12.2
sympy                         1.7.1
tables                        3.7.0
tabulate                      0.8.10
tblib                         1.7.0
tenacity                      8.1.0
tensorboard                   2.9.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.9.2
tensorflow-datasets           4.6.0
tensorflow-estimator          2.9.0
tensorflow-gcs-config         2.9.1
tensorflow-hub                0.12.0
tensorflow-io-gcs-filesystem  0.27.0
tensorflow-metadata           1.10.0
tensorflow-probability        0.16.0
termcolor                     2.0.1
terminado                     0.13.3
testpath                      0.6.0
text-unidecode                1.3
textblob                      0.15.3
thinc                         8.1.5
threadpoolctl                 3.1.0
tifffile                      2021.11.2
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         1.12.1+cu113
torchaudio                    0.12.1+cu113
torchsummary                  1.5.1
torchtext                     0.13.1
torchvision                   0.13.1+cu113
tornado                       5.1.1
tqdm                          4.64.1
traitlets                     5.1.1
tweepy                        3.10.0
typeguard                     2.7.1
typer                         0.4.2
typing-extensions             4.1.1
tzlocal                       1.5.1
uritemplate                   3.0.1
urllib3                       1.24.3
vega-datasets                 0.9.0
wasabi                        0.10.1
wcwidth                       0.2.5
webargs                       8.2.0
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.37.1
widgetsnbextension            3.6.1
wordcloud                     1.8.2.2
wrapt                         1.14.1
xarray                        0.20.2
xarray-einstats               0.2.2
xgboost                       0.90
xkit                          0.0.0
xlrd                          1.1.0
xlwt                          1.3.0
yarl                          1.8.1
yellowbrick                   1.5
zict                          2.2.0
zipp                          3.10.0

In [ ]:
!pip install yfinance --quiet

In [ ]:
import yfinance as yf

In [ ]:
history = yf.Ticker('AAPL').history()
history.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-10-31 00:00:00-04:00,152.906350,153.984563,151.668398,153.086044,97943200,0.00,0
2022-11-01 00:00:00-04:00,154.823169,155.192551,148.883026,150.400497,80379300,0.00,0
2022-11-02 00:00:00-04:00,148.703316,151.917985,144.759861,144.789810,93604600,0.00,0
2022-11-03 00:00:00-04:00,141.824736,142.563516,138.520220,138.650009,97918500,0.00,0
2022-11-04 00:00:00-04:00,142.089996,142.669998,134.380005,138.380005,140716700,0.23,0

In [ ]:
import pandas as pd

In [ ]:
pd.options.display.float_format = '{: .2f}'.format

In [ ]:
history.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-10-31 00:00:00-04:00,152.91,153.98,151.67,153.09,97943200,0.00,0
2022-11-01 00:00:00-04:00,154.82,155.19,148.88,150.40,80379300,0.00,0
2022-11-02 00:00:00-04:00,148.70,151.92,144.76,144.79,93604600,0.00,0
2022-11-03 00:00:00-04:00,141.82,142.56,138.52,138.65,97918500,0.00,0
2022-11-04 00:00:00-04:00,142.09,142.67,134.38,138.38,140716700,0.23,0

In [ ]:
history.index = history.index.date
history.tail()

              Open    High     Low   Close     Volume  Dividends  Stock Splits
2022-10-31  152.91  153.98  151.67  153.09   97943200       0.00             0
2022-11-01  154.82  155.19  148.88  150.40   80379300       0.00             0
2022-11-02  148.70  151.92  144.76  144.79   93604600       0.00             0
2022-11-03  141.82  142.56  138.52  138.65   97918500       0.00             0
2022-11-04  142.09  142.67  134.38  138.38  140716700       0.23             0

In [ ]:
history.describe()

         Open    High     Low   Close        Volume  Dividends  Stock Splits
count   23.00   23.00   23.00   23.00         23.00      23.00         23.00
mean   144.60  147.01  142.27  144.54   90364386.96       0.01          0.00
std      4.81    4.86    4.76    5.12   23998997.23       0.05          0.00
min    134.77  140.13  134.15  138.11   61758300.00       0.00          0.00
25%    141.64  142.77  138.43  140.02   75440450.00       0.00          0.00
50%    143.83  146.46  142.41  143.62   85859100.00       0.00          0.00
75%    147.89  150.86  145.37  148.06   97930850.00       0.00          0.00
max    154.82  157.24  151.67  155.48  164762400.00       0.23          0.00

In [ ]:
history.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 2022-10-05 to 2022-11-04
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          23 non-null     float64
 1   High          23 non-null     float64
 2   Low           23 non-null     float64
 3   Close         23 non-null     float64
 4   Volume        23 non-null     int64
 5   Dividends     23 non-null     float64
 6   Stock Splits  23 non-null     int64
dtypes: float64(5), int64(2)
memory usage: 1.4+ KB

In [ ]:
history.Close.tail()

2022-10-31    153.09
2022-11-01    150.40
2022-11-02    144.79
2022-11-03    138.65
2022-11-04    138.38
Name: Close, dtype: float64

In [ ]:
history['Close'].tail()

2022-10-31    153.09
2022-11-01    150.40
2022-11-02    144.79
2022-11-03    138.65
2022-11-04    138.38
Name: Close, dtype: float64

In [ ]:
history.rolling(5).max()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
2022-10-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-10-11,145.57,147.30,144.98,146.16,85859100.00,0.00,0.00
2022-10-12,145.57,147.30,144.98,145.19,85859100.00,0.00,0.00
2022-10-13,142.30,143.35,139.22,142.75,113224000.00,0.00,0.00
2022-10-14,144.07,144.28,138.34,142.75,113224000.00,0.00,0.00
2022-10-17,144.07,144.28,140.04,142.75,113224000.00,0.00,0.00
2022-10-18,145.25,146.46,140.38,143.51,113224000.00,0.00,0.00
2022-10-19,145.25,146.46,141.27,143.62,113224000.00,0.00,0.00
2022-10-20,145.25,146.46,142.41,143.62,99136600.00,0.00,0.00
2022-10-21,145.25,147.61,142.41,147.03,99136600.00,0.00,0.00
2022-10-24,146.95,149.98,145.76,149.20,99136600.00,0.00,0.00
2022-10-25,149.84,152.24,149.11,152.09,86464700.00,0.00,0.00
2022-10-26,150.71,152.24,149.11,152.09,88194300.00,0.00,0.00
2022-10-27,150.71,152.24,149.11,152.09,109180200.00,0.00,0.00
2022-10-28,150.71,157.24,149.11,155.48,164762400.00,0.00,0.00
2022-10-31,152.91,157.24,151.67,155.48,164762400.00,0.00,0.00
2022-11-01,154.82,157.24,151.67,155.48,164762400.00,0.00,0.00
2022-11-02,154.82,157.24,151.67,155.48,164762400.00,0.00,0.00
2022-11-03,154.82,157.24,151.67,155.48,164762400.00,0.00,0.00
2022-11-04,154.82,155.19,151.67,153.09,140716700.00,0.23,0.00

In [ ]:
!pip install pyupbit --quiet

     |████████████████████████████████| 106 kB 7.7 MB/s

In [ ]:
import pyupbit

In [ ]:
pyupbit.get_ohlcv()

,open,high,low,close,volume,value
2022-04-22 09:00:00,50805000.00,51000000.00,49526000.00,49937000.00,3309.38,166518417330.13
2022-04-23 09:00:00,49937000.00,50290000.00,49466000.00,49742000.00,1905.15,94878858638.68
2022-04-24 09:00:00,49723000.00,50211000.00,49300000.00,49620000.00,1658.62,82647094726.20
2022-04-25 09:00:00,49620000.00,50993000.00,48600000.00,50614000.00,4209.04,208005727805.64
2022-04-26 09:00:00,50614000.00,51193000.00,48300000.00,48777000.00,4171.12,207571264467.20
...,...,...,...,...,...,...
2022-11-03 09:00:00,28632000.00,28900000.00,28443000.00,28693000.00,6757.69,194086875436.71
2022-11-04 09:00:00,28685000.00,29679000.00,28683000.00,29388000.00,7964.12,231718138685.04
2022-11-05 09:00:00,29388000.00,29870000.00,29304000.00,29756000.00,5550.08,164967206076.35
2022-11-06 09:00:00,29756000.00,29869000.00,29400000.00,29473000.00,3135.47,93055406232.25
2022-11-07 09:00:00,29470000.00,29658000.00,29380000.00,29401000.00,1032.21,30442134210.01